-- V1.3 Stage3 初始治理（确定性规则 + 人工确认语义 reviewed_by=MASTERDATA_ADMIN）
BEGIN;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000001', '【鱼子酱洗护组合】弹动鱼子酱氨基酸洗发水发膜套装控油蓬松留香D', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3523538019611183417', '【鱼子酱洗护组合】弹动鱼子酱氨基酸洗发水发膜套装控油蓬松留香D', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000001'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000002', '弹动人参茶树纯露洗发水护发素套装控油留香蓬松洗护发膜洗发露D', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='RENSHEN'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3658584866435510760', '弹动人参茶树纯露洗发水护发素套装控油留香蓬松洗护发膜洗发露D', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000002'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000003', '弹动鱼子酱氨基酸洗发水推荐发膜套装控油蓬松持久留香头发洗发露', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3822240520315470154', '弹动鱼子酱氨基酸洗发水推荐发膜套装控油蓬松持久留香头发洗发露', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000003'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000004', '弹动鱼子酱氨基酸发膜套装控油蓬松持久留香柔顺护发素头发洗发水', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3777721060405936555', '弹动鱼子酱氨基酸发膜套装控油蓬松持久留香柔顺护发素头发洗发水', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000004'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000005', '【夏季推荐】弹动鱼子酱氨基酸人参纯露洗发水套装蓬松控油洗发露D', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3697011738043089300', '【夏季推荐】弹动鱼子酱氨基酸人参纯露洗发水套装蓬松控油洗发露D', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000005'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000006', '弹动鱼子酱氨基酸洗发水发膜套装控油蓬松持久留香头发洗发水推荐', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3700110037105115368', '弹动鱼子酱氨基酸洗发水发膜套装控油蓬松持久留香头发洗发水推荐', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000006'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000007', '弹动鱼子酱氨基酸洗发水发膜鱼子酱奢护养护蓬松头发洗发露推荐', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3809452311126868036', '弹动鱼子酱氨基酸洗发水发膜鱼子酱奢护养护蓬松头发洗发露推荐', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000007'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000008', '弹动人参纯露洗护洗发水男士护发素控油蓬松柔顺留香发膜洗头膏K', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='RENSHEN'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3679939786237411406', '弹动人参纯露洗护洗发水男士护发素控油蓬松柔顺留香发膜洗头膏K', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000008'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000009', '弹动椰子蓬松洗护系列控油蓬松留香双0配方顺养护修护洗发水ZB', '弹动', NULL, 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3801439362340749595', '弹动椰子蓬松洗护系列控油蓬松留香双0配方顺养护修护洗发水ZB', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000009'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000010', '弹动香水沐浴露持久留香保湿补水深层清洁润肤清爽香氛沐浴油D', '弹动', NULL, 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3638336876483616833', '弹动香水沐浴露持久留香保湿补水深层清洁润肤清爽香氛沐浴油D', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000010'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000011', '弹动鱼子酱氨基酸洗护套装多效洗发水护发素蓬松顺滑养护洗头膏', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3547241828338273156', '弹动鱼子酱氨基酸洗护套装多效洗发水护发素蓬松顺滑养护洗头膏', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000011'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000012', '弹动鱼子酱氨基酸洗发水发膜柔顺蓬松去屑持久留香蓬松洗发水ZB', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3740745940508738168', '弹动鱼子酱氨基酸洗发水发膜柔顺蓬松去屑持久留香蓬松洗发水ZB', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000012'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000013', '【鱼子酱洗护组合】弹动鱼子酱氨基酸洗发水发膜套装蓬松控油留香D', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3588464918741052956', '【鱼子酱洗护组合】弹动鱼子酱氨基酸洗发水发膜套装蓬松控油留香D', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000013'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000014', '弹动洋甘菊二硫化硒洗头露留香控油净澈去屑洗发水清爽头发洗发水', '弹动', NULL, 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3726899071131189459', '弹动洋甘菊二硫化硒洗头露留香控油净澈去屑洗发水清爽头发洗发水', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000014'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000015', '弹动鱼子酱氨基酸洗护套装控油蓬松持久留香洗发水推荐S11', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3777875340127502708', '弹动鱼子酱氨基酸洗护套装控油蓬松持久留香洗发水推荐S11', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000015'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3823544272729276453', '弹动鱼子酱氨基酸洗护套装控油蓬松持久留香洗发水推荐S11', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000015'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000016', '弹动鱼子酱氨基酸洗发水控油蓬松洗头膏发膜持久留香洗护洗发水K', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3587673057818478364', '弹动鱼子酱氨基酸洗发水控油蓬松洗头膏发膜持久留香洗护洗发水K', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000016'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000017', '弹动人参茶树纯露洗发水发膜控油防断蓬松舒缓修护高级洗发露ZB', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='RENSHEN'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3705349405390536872', '弹动人参茶树纯露洗发水发膜控油防断蓬松舒缓修护高级洗发露ZB', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000017'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000018', '弹动人参茶树纯露洗发水柔顺控油蓬松保湿持久控油头发洗发露推荐', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='RENSHEN'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3648045027000734535', '弹动人参茶树纯露洗发水柔顺控油蓬松保湿持久控油头发洗发露推荐', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000018'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000019', '【618官方现货】弹动椰子蓬松洗发水发膜洗护套装控油蓬松留香ZB', '弹动', NULL, 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3772718628269589040', '【618官方现货】弹动椰子蓬松洗发水发膜洗护套装控油蓬松留香ZB', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000019'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000020', '弹动乳酸菌白松露护发素洗发水套装去屑控油蓬松洗发露香氛发膜D', '弹动', NULL, 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3639120757432389786', '弹动乳酸菌白松露护发素洗发水套装去屑控油蓬松洗发露香氛发膜D', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000020'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000021', '【618官方现货】弹动椰子蓬松洗发洗护套装控油蓬松双0配方洗发露ZB', '弹动', NULL, 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3770861890343928034', '【618官方现货】弹动椰子蓬松洗发洗护套装控油蓬松双0配方洗发露ZB', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000021'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000022', '弹动鱼子酱氨基酸洗护套装控油蓬松持久留香头发洗发水推荐fnn', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3807772094083760551', '弹动鱼子酱氨基酸洗护套装控油蓬松持久留香头发洗发水推荐fnn', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000022'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000023', '弹动鱼子酱洗发水氨基酸洗护养护修护高级洗头控油洗发水洗发露', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3703675787824726413', '弹动鱼子酱洗发水氨基酸洗护养护修护高级洗头控油洗发水洗发露', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000023'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000024', '弹动鱼子酱氨基酸洗发水发膜蓬松控油蓬松头发留香洗头洗发露DXS', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3710114497751548312', '弹动鱼子酱氨基酸洗发水发膜蓬松控油蓬松头发留香洗头洗发露DXS', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000024'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000025', '弹动鱼子酱氨基酸洗发水蓬松控油高颅顶洗护套装香氛洗发膏护发素', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3587133030038434554', '弹动鱼子酱氨基酸洗发水蓬松控油高颅顶洗护套装香氛洗发膏护发素', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000025'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000026', '弹动椰子蓬松洗发水发膜套装柔顺养护控油蓬松持久留香双0配方Q', '弹动', NULL, 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3820197851166802403', '弹动椰子蓬松洗发水发膜套装柔顺养护控油蓬松持久留香双0配方Q', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000026'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3817213016374641273', '弹动椰子蓬松洗发水发膜套装柔顺养护控油蓬松持久留香双0配方Q', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000026'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000027', '弹动椰子洗发水推荐护发素控油双0配方多效柔顺养护修护洗头膏K', '弹动', NULL, 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3588797686071064629', '弹动椰子洗发水推荐护发素控油双0配方多效柔顺养护修护洗头膏K', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000027'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3627041614897225165', '弹动椰子洗发水推荐护发素控油双0配方多效柔顺养护修护洗头膏K', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000027'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000028', '弹动鱼子酱氨基酸控油蓬松洗发水保湿养护发膜持久留香洗发推荐K', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3705534222212137311', '弹动鱼子酱氨基酸控油蓬松洗发水保湿养护发膜持久留香洗发推荐K', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000028'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000029', '弹动鱼子酱氨基酸洗护套装沐浴露发膜养护蓬松持久留香洗头洗发露', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3763969687487119778', '弹动鱼子酱氨基酸洗护套装沐浴露发膜养护蓬松持久留香洗头洗发露', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000029'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000030', '弹动香水沐浴露清爽保湿润肤补水清爽沐浴露滋润沐浴乳持久留香D', '弹动', NULL, 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3629845627254502659', '弹动香水沐浴露清爽保湿润肤补水清爽沐浴露滋润沐浴乳持久留香D', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000030'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000031', '弹动人参茶树纯露发膜控油蓬松持久发护发保湿亮泽留香护发素', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='RENSHEN'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3696242434330722549', '弹动人参茶树纯露发膜控油蓬松持久发护发保湿亮泽留香护发素', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000031'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000032', '弹动防脱固发洗发水深层清洁持久持久留香保湿柔顺洗头洗发膏推荐', '弹动', NULL, 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3760428368814801126', '弹动防脱固发洗发水深层清洁持久持久留香保湿柔顺洗头洗发膏推荐', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000032'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000033', '弹动玫瑰纯露香氛香发喷雾72小时持久留香保湿护发改善干枯毛躁ZB', '弹动', NULL, 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3683235396432560394', '弹动玫瑰纯露香氛香发喷雾72小时持久留香保湿护发改善干枯毛躁ZB', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000033'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3685124640683982947', '弹动玫瑰纯露香氛香发喷雾72小时持久留香保湿护发改善干枯毛躁', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000033'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.master_product (master_product_code, master_product_name, brand_name, product_line_id, product_status, enabled, notes) VALUES
  ('MP000034', '弹动鱼子酱油养前导发膜保湿柔顺护理头发护发素持久留香防断发', '弹动', (SELECT product_line_id FROM meta.product_line WHERE product_line_code='YIZIJIANG'), 'ACTIVE', true, '初始治理：标准化归组人工确认') ON CONFLICT (master_product_code) DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 1, '3686804827561656659', '弹动鱼子酱油养前导发膜保湿柔顺护理头发护发素持久留香防断发', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000034'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
INSERT INTO meta.platform_product_mapping (platform_code, shop_id, platform_product_id, platform_product_name_snapshot, master_product_id, mapping_status, mapping_source, confidence_score, valid_from, enabled, reviewed_by, reviewed_at, notes) VALUES
  ('douyin', 2, '3653388860190252499', '弹动鱼子酱油养前导发膜保湿柔顺护理头发护发素持久留香防断发', (SELECT master_product_id FROM meta.master_product WHERE master_product_code='MP000034'), 'CONFIRMED', 'MANUAL', 1.0000, '2026-06-01', true, 'MASTERDATA_ADMIN', now(), '初始治理人工确认') ON CONFLICT DO NOTHING;
COMMIT;