-- 重建中文View: shop_id -> shop_name
BEGIN;

CREATE OR REPLACE VIEW "中文数据"."抖音载体日报" AS
SELECT
    row_id AS "数据行ID",
    shop_name AS "店铺名称",
    biz_date AS "日期",
    sale_scope AS "自营/合作",
    carrier_type AS "载体类型",
    account_channel AS "账号/渠道",
    douyin_account_id AS "抖音号",
    transaction_amount AS "成交金额",
    user_pay_amount AS "用户支付金额",
    settlement_amount AS "结算金额",
    transaction_refund_amount_pay_time AS "成交退款金额(支付时间)",
    refund_amount_pay_time AS "退款金额(支付时间)",
    refund_rate_pay_time AS "退款率(支付时间)",
    ad_attributed_transaction_amount AS "投放贡献成交金额",
    ad_attributed_transaction_share AS "投放贡献成交占比",
    ad_spend_shop_promoted AS "投放消耗(店铺被投)",
    ad_spend_rate_net_refund_shop_promoted AS "投放费比(剔除退款、店铺被投)",
    exposure_to_click_rate_users AS "商品曝光-点击转化率(人数)",
    click_to_transaction_rate_users AS "商品点击-成交转化率(人数)",
    smart_coupon_amount AS "智能优惠券金额",
    platform_subsidy_amount AS "平台补贴金额",
    creator_subsidy_amount AS "达人补贴金额",
    presale_deposit_amount AS "预售定金",
    transaction_order_count AS "成交订单数",
    transaction_item_count AS "成交件数",
    avg_item_amount AS "件单价",
    transaction_buyer_count AS "成交人数",
    avg_customer_amount AS "客单价",
    net_transaction_amount AS "净成交金额",
    net_transaction_order_count AS "净成交订单量",
    settlement_amount_7d AS "7日结算金额",
    settlement_amount_14d AS "14日结算金额",
    settlement_amount_refund_time AS "结算金额(退款时间)",
    ad_attributed_settlement_amount AS "投放贡献结算金额",
    net_user_pay_amount_pay_time AS "退款后用户支付金额(支付时间)",
    net_smart_coupon_amount_pay_time AS "退款后智能优惠券金额(支付时间)",
    net_platform_subsidy_amount_pay_time AS "退款后平台补贴金额(支付时间)",
    net_creator_subsidy_amount_pay_time AS "退款后达人补贴金额(支付时间)",
    refund_order_count_pay_time AS "退款订单数(支付时间)",
    transaction_refund_amount_refund_time AS "成交退款金额(退款时间)",
    refund_amount_refund_time AS "退款金额(退款时间)",
    refund_order_count_refund_time AS "退款订单数(退款时间)",
    one_hour_transaction_refund_amount_pay_time AS "1小时成交退款金额(支付时间)",
    one_hour_refund_order_count_pay_time AS "1小时退款订单数(支付时间)",
    one_hour_refund_rate_pay_time AS "1小时退款率(支付时间)",
    ad_attributed_transaction_refund_amount_pay_time AS "投放贡献成交退款金额(支付时间)",
    ad_attributed_refund_rate_pay_time AS "投放部分退款率(支付时间)",
    product_exposure_count AS "商品曝光次数",
    product_click_count AS "商品点击次数",
    exposure_to_click_rate_events AS "商品曝光-点击转化率(次数)",
    click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    exposure_to_transaction_rate_events AS "商品曝光-成交转化率(次数)",
    product_exposure_user_count AS "商品曝光人数",
    product_click_user_count AS "商品点击人数",
    exposure_to_transaction_rate_users AS "商品曝光-成交转化率(人数)",
    user_pay_amount_per_1000_exposures AS "千次曝光用户支付金额",
    ad_spend_shop_bound AS "投放消耗(店铺绑定)",
    platform_commission_settlement AS "平台佣金(结算口径)",
    creator_commission_settlement AS "达人佣金(结算口径)",
    ad_spend_rate_shop_bound AS "投放费比(店铺绑定)",
    ad_spend_rate_shop_promoted AS "投放费比(店铺被投)",
    ad_spend_rate_net_refund_shop_bound AS "投放费比(剔除退款、店铺绑定)",
    total_expense_rate_shop_bound AS "综合费比(店铺绑定)",
    total_expense_rate_shop_promoted AS "综合费比(店铺被投)",
    total_expense_rate_net_refund_shop_bound AS "综合费比(剔除退款、店铺绑定)",
    total_expense_rate_net_refund_shop_promoted AS "综合费比(剔除退款、店铺被投)",
    batch_id AS "导入批次ID",
    source_sheet_name AS "源工作表名称",
    source_row_number AS "源文件行号",
    imported_at AS "写入时间",
    shop_name AS ""
FROM core.douyin_carrier_daily;

CREATE OR REPLACE VIEW "中文数据"."抖音账号日报" AS
SELECT
    row_id AS "数据行ID",
    shop_name AS "店铺名称",
    biz_date AS "日期",
    account_name AS "账号名称",
    account_type AS "账号类型",
    sale_scope AS "自营/合作",
    douyin_account_id AS "抖音号",
    transaction_amount AS "成交金额",
    user_pay_amount AS "用户支付金额",
    settlement_amount AS "结算金额",
    transaction_refund_amount_pay_time AS "成交退款金额(支付时间)",
    refund_amount_pay_time AS "退款金额(支付时间)",
    refund_rate_pay_time AS "退款率(支付时间)",
    ad_attributed_transaction_amount AS "投放贡献成交金额",
    ad_attributed_transaction_share AS "投放贡献成交占比",
    ad_spend_shop_promoted AS "投放消耗(店铺被投)",
    ad_spend_rate_net_refund_shop_promoted AS "投放费比(剔除退款、店铺被投)",
    exposure_to_click_rate_users AS "商品曝光-点击转化率(人数)",
    click_to_transaction_rate_users AS "商品点击-成交转化率(人数)",
    smart_coupon_amount AS "智能优惠券金额",
    platform_subsidy_amount AS "平台补贴金额",
    creator_subsidy_amount AS "达人补贴金额",
    presale_deposit_amount AS "预售定金",
    transaction_order_count AS "成交订单数",
    transaction_item_count AS "成交件数",
    avg_item_amount AS "件单价",
    transaction_buyer_count AS "成交人数",
    avg_customer_amount AS "客单价",
    net_transaction_amount AS "净成交金额",
    net_transaction_order_count AS "净成交订单量",
    settlement_amount_7d AS "7日结算金额",
    settlement_amount_14d AS "14日结算金额",
    settlement_amount_refund_time AS "结算金额(退款时间)",
    ad_attributed_settlement_amount AS "投放贡献结算金额",
    net_user_pay_amount_pay_time AS "退款后用户支付金额(支付时间)",
    net_smart_coupon_amount_pay_time AS "退款后智能优惠券金额(支付时间)",
    net_platform_subsidy_amount_pay_time AS "退款后平台补贴金额(支付时间)",
    net_creator_subsidy_amount_pay_time AS "退款后达人补贴金额(支付时间)",
    refund_order_count_pay_time AS "退款订单数(支付时间)",
    transaction_refund_amount_refund_time AS "成交退款金额(退款时间)",
    refund_amount_refund_time AS "退款金额(退款时间)",
    refund_order_count_refund_time AS "退款订单数(退款时间)",
    one_hour_transaction_refund_amount_pay_time AS "1小时成交退款金额(支付时间)",
    one_hour_refund_order_count_pay_time AS "1小时退款订单数(支付时间)",
    one_hour_refund_rate_pay_time AS "1小时退款率(支付时间)",
    ad_attributed_transaction_refund_amount_pay_time AS "投放贡献成交退款金额(支付时间)",
    ad_attributed_refund_rate_pay_time AS "投放部分退款率(支付时间)",
    product_exposure_count AS "商品曝光次数",
    product_click_count AS "商品点击次数",
    exposure_to_click_rate_events AS "商品曝光-点击转化率(次数)",
    click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    exposure_to_transaction_rate_events AS "商品曝光-成交转化率(次数)",
    product_exposure_user_count AS "商品曝光人数",
    product_click_user_count AS "商品点击人数",
    exposure_to_transaction_rate_users AS "商品曝光-成交转化率(人数)",
    user_pay_amount_per_1000_exposures AS "千次曝光用户支付金额",
    ad_spend_shop_bound AS "投放消耗(店铺绑定)",
    platform_commission_settlement AS "平台佣金(结算口径)",
    creator_commission_settlement AS "达人佣金(结算口径)",
    ad_spend_rate_shop_bound AS "投放费比(店铺绑定)",
    ad_spend_rate_shop_promoted AS "投放费比(店铺被投)",
    ad_spend_rate_net_refund_shop_bound AS "投放费比(剔除退款、店铺绑定)",
    total_expense_rate_shop_bound AS "综合费比(店铺绑定)",
    total_expense_rate_shop_promoted AS "综合费比(店铺被投)",
    total_expense_rate_net_refund_shop_bound AS "综合费比(剔除退款、店铺绑定)",
    total_expense_rate_net_refund_shop_promoted AS "综合费比(剔除退款、店铺被投)",
    batch_id AS "导入批次ID",
    source_sheet_name AS "源工作表名称",
    source_row_number AS "源文件行号",
    imported_at AS "写入时间",
    shop_name AS ""
FROM core.douyin_account_daily;

CREATE OR REPLACE VIEW "中文数据"."抖音内容日报" AS
SELECT
    row_id AS "数据行ID",
    shop_name AS "店铺名称",
    biz_date AS "日期",
    selling_type AS "售卖类型",
    carrier_type AS "载体类型",
    content_id AS "ID",
    content_title AS "标题/名称",
    transaction_amount AS "成交金额",
    user_pay_amount AS "用户支付金额",
    settlement_amount AS "结算金额",
    transaction_refund_amount_pay_time AS "成交退款金额(支付时间)",
    refund_amount_pay_time AS "退款金额(支付时间)",
    refund_rate_pay_time AS "退款率(支付时间)",
    ad_attributed_transaction_amount AS "投放贡献成交金额",
    ad_attributed_transaction_share AS "投放贡献成交占比",
    ad_spend_shop_promoted AS "投放消耗(店铺被投)",
    ad_spend_rate_net_refund_shop_promoted AS "投放费比(剔除退款、店铺被投)",
    exposure_to_click_rate_users AS "商品曝光-点击转化率(人数)",
    click_to_transaction_rate_users AS "商品点击-成交转化率(人数)",
    smart_coupon_amount AS "智能优惠券金额",
    platform_subsidy_amount AS "平台补贴金额",
    creator_subsidy_amount AS "达人补贴金额",
    presale_deposit_amount AS "预售定金",
    transaction_order_count AS "成交订单数",
    transaction_item_count AS "成交件数",
    avg_item_amount AS "件单价",
    transaction_buyer_count AS "成交人数",
    avg_customer_amount AS "客单价",
    net_transaction_amount AS "净成交金额",
    net_transaction_order_count AS "净成交订单量",
    settlement_amount_7d AS "7日结算金额",
    settlement_amount_14d AS "14日结算金额",
    settlement_amount_refund_time AS "结算金额(退款时间)",
    ad_attributed_settlement_amount AS "投放贡献结算金额",
    net_user_pay_amount_pay_time AS "退款后用户支付金额(支付时间)",
    net_smart_coupon_amount_pay_time AS "退款后智能优惠券金额(支付时间)",
    net_platform_subsidy_amount_pay_time AS "退款后平台补贴金额(支付时间)",
    net_creator_subsidy_amount_pay_time AS "退款后达人补贴金额(支付时间)",
    refund_order_count_pay_time AS "退款订单数(支付时间)",
    transaction_refund_amount_refund_time AS "成交退款金额(退款时间)",
    refund_amount_refund_time AS "退款金额(退款时间)",
    refund_order_count_refund_time AS "退款订单数(退款时间)",
    one_hour_transaction_refund_amount_pay_time AS "1小时成交退款金额(支付时间)",
    one_hour_refund_order_count_pay_time AS "1小时退款订单数(支付时间)",
    one_hour_refund_rate_pay_time AS "1小时退款率(支付时间)",
    ad_attributed_transaction_refund_amount_pay_time AS "投放贡献成交退款金额(支付时间)",
    ad_attributed_refund_rate_pay_time AS "投放部分退款率(支付时间)",
    product_exposure_count AS "商品曝光次数",
    product_click_count AS "商品点击次数",
    exposure_to_click_rate_events AS "商品曝光-点击转化率(次数)",
    click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    exposure_to_transaction_rate_events AS "商品曝光-成交转化率(次数)",
    product_exposure_user_count AS "商品曝光人数",
    product_click_user_count AS "商品点击人数",
    exposure_to_transaction_rate_users AS "商品曝光-成交转化率(人数)",
    user_pay_amount_per_1000_exposures AS "千次曝光用户支付金额",
    ad_spend_shop_bound AS "投放消耗(店铺绑定)",
    platform_commission_settlement AS "平台佣金(结算口径)",
    creator_commission_settlement AS "达人佣金(结算口径)",
    ad_spend_rate_shop_bound AS "投放费比(店铺绑定)",
    ad_spend_rate_shop_promoted AS "投放费比(店铺被投)",
    ad_spend_rate_net_refund_shop_bound AS "投放费比(剔除退款、店铺绑定)",
    total_expense_rate_shop_bound AS "综合费比(店铺绑定)",
    total_expense_rate_shop_promoted AS "综合费比(店铺被投)",
    total_expense_rate_net_refund_shop_bound AS "综合费比(剔除退款、店铺绑定)",
    total_expense_rate_net_refund_shop_promoted AS "综合费比(剔除退款、店铺被投)",
    batch_id AS "导入批次ID",
    source_sheet_name AS "源工作表名称",
    source_row_number AS "源文件行号",
    imported_at AS "写入时间",
    shop_name AS ""
FROM core.douyin_content_daily;

CREATE OR REPLACE VIEW "中文数据"."抖音终端日报" AS
SELECT
    row_id AS "数据行ID",
    shop_name AS "店铺名称",
    biz_date AS "日期",
    terminal_type AS "终端类型",
    selling_type AS "售卖类型",
    transaction_amount AS "成交金额",
    user_pay_amount AS "用户支付金额",
    settlement_amount AS "结算金额",
    transaction_order_count AS "成交订单数",
    transaction_refund_amount_pay_time AS "成交退款金额(支付时间)",
    refund_rate_pay_time AS "退款率(支付时间)",
    product_exposure_count AS "商品曝光次数",
    product_click_count AS "商品点击次数",
    exposure_to_click_rate_events AS "商品曝光-点击转化率(次数)",
    click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    smart_coupon_amount AS "智能优惠券金额",
    platform_subsidy_amount AS "平台补贴金额",
    creator_subsidy_amount AS "达人补贴金额",
    presale_deposit_amount AS "预售定金",
    transaction_item_count AS "成交件数",
    avg_item_amount AS "件单价",
    settlement_amount_7d AS "7日结算金额",
    settlement_amount_14d AS "14日结算金额",
    settlement_amount_refund_time AS "结算金额(退款时间)",
    ad_attributed_settlement_amount AS "投放贡献结算金额",
    net_user_pay_amount_pay_time AS "退款后用户支付金额(支付时间)",
    net_smart_coupon_amount_pay_time AS "退款后智能优惠券金额(支付时间)",
    net_platform_subsidy_amount_pay_time AS "退款后平台补贴金额(支付时间)",
    net_creator_subsidy_amount_pay_time AS "退款后达人补贴金额(支付时间)",
    refund_amount_pay_time AS "退款金额(支付时间)",
    refund_order_count_pay_time AS "退款订单数(支付时间)",
    transaction_refund_amount_refund_time AS "成交退款金额(退款时间)",
    refund_amount_refund_time AS "退款金额(退款时间)",
    refund_order_count_refund_time AS "退款订单数(退款时间)",
    one_hour_transaction_refund_amount_pay_time AS "1小时成交退款金额(支付时间)",
    one_hour_refund_order_count_pay_time AS "1小时退款订单数(支付时间)",
    one_hour_refund_rate_pay_time AS "1小时退款率(支付时间)",
    exposure_to_transaction_rate_events AS "商品曝光-成交转化率(次数)",
    user_pay_amount_per_1000_exposures AS "千次曝光用户支付金额",
    batch_id AS "导入批次ID",
    source_sheet_name AS "源工作表名称",
    source_row_number AS "源文件行号",
    imported_at AS "写入时间",
    shop_name AS ""
FROM core.douyin_terminal_daily;

CREATE OR REPLACE VIEW "中文数据"."抖音类目日报" AS
SELECT
    row_id AS "数据行ID",
    shop_name AS "店铺名称",
    biz_date AS "日期",
    category_level_1 AS "一级类目",
    category_level_2 AS "二级类目",
    category_level_3 AS "三级类目",
    category_level_4 AS "四级类目",
    user_pay_amount AS "用户支付金额",
    avg_transaction_order_amount AS "成交笔单价",
    click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    refund_amount_pay_time AS "退款金额(支付时间)",
    refund_rate_pay_time AS "退款率(支付时间)",
    batch_id AS "导入批次ID",
    source_sheet_name AS "源工作表名称",
    source_row_number AS "源文件行号",
    imported_at AS "写入时间",
    shop_name AS ""
FROM core.douyin_category_daily;

CREATE OR REPLACE VIEW "中文数据"."抖音商品日报" AS
SELECT
    row_id AS "数据行ID",
    shop_name AS "店铺名称",
    biz_date AS "日期",
    product_name AS "商品名称",
    product_id AS "商品编号",
    carrier_type AS "载体类型",
    user_pay_amount AS "用户支付金额",
    avg_transaction_order_amount AS "成交笔单价",
    click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    refund_amount_pay_time AS "退款金额(支付时间)",
    refund_rate_pay_time AS "退款率(支付时间)",
    smart_coupon_amount AS "智能优惠券金额",
    platform_subsidy_amount AS "电商平台补贴金额",
    net_smart_coupon_amount_pay_time AS "退款后智能优惠券金额(支付时间)",
    net_platform_subsidy_amount_pay_time AS "退款后电商平台补贴金额(支付时间)",
    batch_id AS "导入批次ID",
    source_sheet_name AS "源工作表名称",
    source_row_number AS "源文件行号",
    imported_at AS "写入时间",
    shop_name AS ""
FROM core.douyin_product_daily;

CREATE OR REPLACE VIEW "中文数据"."抖音价格带日报" AS
SELECT
    row_id AS "数据行ID",
    shop_name AS "店铺名称",
    biz_date AS "日期",
    price_band AS "价格带",
    user_pay_amount AS "用户支付金额",
    avg_transaction_order_amount AS "成交笔单价",
    click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    batch_id AS "导入批次ID",
    source_sheet_name AS "源工作表名称",
    source_row_number AS "源文件行号",
    imported_at AS "写入时间",
    shop_name AS ""
FROM core.douyin_price_band_daily;

CREATE OR REPLACE VIEW "中文数据"."抖音人群日报" AS
SELECT
    row_id AS "数据行ID",
    shop_name AS "店铺名称",
    biz_date AS "日期",
    audience_type AS "人群类型",
    carrier_type AS "载体类型",
    user_pay_amount AS "用户支付金额",
    transaction_buyer_count AS "成交人数",
    avg_customer_amount AS "客单价",
    transaction_order_count AS "成交订单数",
    repeat_user_repeat_rate AS "复购用户复购率",
    batch_id AS "导入批次ID",
    source_sheet_name AS "源工作表名称",
    source_row_number AS "源文件行号",
    imported_at AS "写入时间",
    shop_name AS ""
FROM core.douyin_audience_daily;

CREATE OR REPLACE VIEW "中文数据"."导入批次记录" AS
SELECT
    batch_id AS "导入批次ID",
    platform_code AS "平台编码",
    shop_name AS "店铺名称",
    source_file_name AS "源文件名",
    source_file_path AS "源文件路径",
    file_sha256 AS "文件SHA256",
    period_start AS "周期开始",
    period_end AS "周期结束",
    import_mode AS "导入模式",
    import_status AS "导入状态",
    source_row_count AS "源文件行数",
    inserted_row_count AS "写入行数",
    error_message AS "错误信息",
    imported_at AS "写入时间",
    shop_name AS ""
FROM audit.import_batch;

COMMIT;