-- 重建9张业务中文View: JOIN meta.shop 显示店铺名称
BEGIN;

DROP VIEW IF EXISTS "中文数据"."抖音成交日报";
CREATE VIEW "中文数据"."抖音成交日报" AS
SELECT
    t.row_id AS "数据行ID",
    s.shop_name AS "店铺名称",
    t.biz_date AS "日期",
    t.sale_scope AS "成交范围",
    t.carrier_type AS "载体类型",
    t.ad_period AS "投放时段",
    t.user_pay_amount AS "用户支付金额",
    t.net_user_pay_amount_pay_time AS "退款后用户支付金额(支付时间)",
    t.smart_coupon_amount AS "智能优惠券金额",
    t.net_smart_coupon_amount_pay_time AS "退款后智能优惠券金额(支付时间)",
    t.platform_subsidy_amount AS "平台补贴金额",
    t.transaction_order_count AS "成交订单数",
    t.transaction_buyer_count AS "成交人数",
    t.avg_customer_amount AS "客单价",
    t.transaction_amount AS "成交金额",
    t.net_transaction_amount AS "净成交金额",
    t.refund_amount_refund_time AS "退款金额(退款时间)",
    t.transaction_refund_amount_refund_time AS "成交退款金额(退款时间)",
    t.refund_order_count_refund_time AS "退款订单数(退款时间)",
    t.refund_rate_pay_time AS "退款率(支付时间)",
    t.refund_amount_pay_time AS "退款金额(支付时间)",
    t.transaction_refund_amount_pay_time AS "成交退款金额(支付时间)",
    t.refund_order_count_pay_time AS "退款订单数(支付时间)",
    t.product_exposure_user_count AS "商品曝光人数",
    t.product_click_user_count AS "商品点击人数",
    t.exposure_to_click_rate_users AS "商品曝光-点击转化率(人数)",
    t.click_to_transaction_rate_users AS "商品点击-成交转化率(人数)",
    t.exposure_to_transaction_rate_users AS "商品曝光-成交转化率(人数)",
    t.user_pay_amount_per_1000_exposures AS "千次曝光用户支付金额",
    t.product_exposure_count AS "商品曝光次数",
    t.product_click_count AS "商品点击次数",
    t.exposure_to_click_rate_events AS "商品曝光-点击转化率(次数)",
    t.click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    t.exposure_to_transaction_rate_events AS "商品曝光-成交转化率(次数)",
    t.shipped_user_pay_amount_ship_time AS "发货用户支付金额(发货时间)",
    t.ship_within_2_days_rate AS "两日内发货率",
    t.settlement_amount AS "结算金额",
    t.settlement_amount_refund_time AS "结算金额(退款时间)",
    t.settlement_amount_7d AS "7日结算金额",
    t.settlement_amount_14d AS "14日结算金额",
    t.net_creator_subsidy_amount_pay_time AS "退款后达人补贴金额(支付时间)",
    t.creator_subsidy_amount AS "达人补贴金额",
    t.presale_deposit_amount AS "预售定金",
    t.transaction_item_count AS "成交件数",
    t.avg_item_amount AS "件单价",
    t.net_transaction_order_count AS "净成交订单量",
    t.pre_shipment_refund_rate_pay_time AS "发货前退款率(支付时间)",
    t.unreceived_refund_rate_pay_time AS "未收货退款率(支付时间)",
    t.received_refund_rate_pay_time AS "已收货退款率(支付时间)",
    t.received_return_refund_rate_pay_time AS "已收货退货退款率(支付时间)",
    t.one_hour_transaction_refund_amount_pay_time AS "1小时成交退款金额(支付时间)",
    t.one_hour_refund_order_count_pay_time AS "1小时退款订单数(支付时间)",
    t.one_hour_refund_rate_pay_time AS "1小时成交退款率(支付时间)",
    t.net_platform_subsidy_amount_pay_time AS "退款后电商平台补贴金额(支付时间)",
    t.batch_id AS "导入批次ID",
    t.source_sheet_name AS "源工作表名称",
    t.source_row_number AS "源文件行号",
    t.imported_at AS "写入时间"
FROM core.douyin_deal_daily t
JOIN meta.shop s ON t.shop_id = s.shop_id;

DROP VIEW IF EXISTS "中文数据"."抖音载体日报";
CREATE VIEW "中文数据"."抖音载体日报" AS
SELECT
    t.row_id AS "数据行ID",
    s.shop_name AS "店铺名称",
    t.biz_date AS "日期",
    t.sale_scope AS "自营/合作",
    t.carrier_type AS "载体类型",
    t.account_channel AS "账号/渠道",
    t.douyin_account_id AS "抖音号",
    t.transaction_amount AS "成交金额",
    t.user_pay_amount AS "用户支付金额",
    t.settlement_amount AS "结算金额",
    t.transaction_refund_amount_pay_time AS "成交退款金额(支付时间)",
    t.refund_amount_pay_time AS "退款金额(支付时间)",
    t.refund_rate_pay_time AS "退款率(支付时间)",
    t.ad_attributed_transaction_amount AS "投放贡献成交金额",
    t.ad_attributed_transaction_share AS "投放贡献成交占比",
    t.ad_spend_shop_promoted AS "投放消耗(店铺被投)",
    t.ad_spend_rate_net_refund_shop_promoted AS "投放费比(剔除退款、店铺被投)",
    t.exposure_to_click_rate_users AS "商品曝光-点击转化率(人数)",
    t.click_to_transaction_rate_users AS "商品点击-成交转化率(人数)",
    t.smart_coupon_amount AS "智能优惠券金额",
    t.platform_subsidy_amount AS "平台补贴金额",
    t.creator_subsidy_amount AS "达人补贴金额",
    t.presale_deposit_amount AS "预售定金",
    t.transaction_order_count AS "成交订单数",
    t.transaction_item_count AS "成交件数",
    t.avg_item_amount AS "件单价",
    t.transaction_buyer_count AS "成交人数",
    t.avg_customer_amount AS "客单价",
    t.net_transaction_amount AS "净成交金额",
    t.net_transaction_order_count AS "净成交订单量",
    t.settlement_amount_7d AS "7日结算金额",
    t.settlement_amount_14d AS "14日结算金额",
    t.settlement_amount_refund_time AS "结算金额(退款时间)",
    t.ad_attributed_settlement_amount AS "投放贡献结算金额",
    t.net_user_pay_amount_pay_time AS "退款后用户支付金额(支付时间)",
    t.net_smart_coupon_amount_pay_time AS "退款后智能优惠券金额(支付时间)",
    t.net_platform_subsidy_amount_pay_time AS "退款后平台补贴金额(支付时间)",
    t.net_creator_subsidy_amount_pay_time AS "退款后达人补贴金额(支付时间)",
    t.refund_order_count_pay_time AS "退款订单数(支付时间)",
    t.transaction_refund_amount_refund_time AS "成交退款金额(退款时间)",
    t.refund_amount_refund_time AS "退款金额(退款时间)",
    t.refund_order_count_refund_time AS "退款订单数(退款时间)",
    t.one_hour_transaction_refund_amount_pay_time AS "1小时成交退款金额(支付时间)",
    t.one_hour_refund_order_count_pay_time AS "1小时退款订单数(支付时间)",
    t.one_hour_refund_rate_pay_time AS "1小时退款率(支付时间)",
    t.ad_attributed_transaction_refund_amount_pay_time AS "投放贡献成交退款金额(支付时间)",
    t.ad_attributed_refund_rate_pay_time AS "投放部分退款率(支付时间)",
    t.product_exposure_count AS "商品曝光次数",
    t.product_click_count AS "商品点击次数",
    t.exposure_to_click_rate_events AS "商品曝光-点击转化率(次数)",
    t.click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    t.exposure_to_transaction_rate_events AS "商品曝光-成交转化率(次数)",
    t.product_exposure_user_count AS "商品曝光人数",
    t.product_click_user_count AS "商品点击人数",
    t.exposure_to_transaction_rate_users AS "商品曝光-成交转化率(人数)",
    t.user_pay_amount_per_1000_exposures AS "千次曝光用户支付金额",
    t.ad_spend_shop_bound AS "投放消耗(店铺绑定)",
    t.platform_commission_settlement AS "平台佣金(结算口径)",
    t.creator_commission_settlement AS "达人佣金(结算口径)",
    t.ad_spend_rate_shop_bound AS "投放费比(店铺绑定)",
    t.ad_spend_rate_shop_promoted AS "投放费比(店铺被投)",
    t.ad_spend_rate_net_refund_shop_bound AS "投放费比(剔除退款、店铺绑定)",
    t.total_expense_rate_shop_bound AS "综合费比(店铺绑定)",
    t.total_expense_rate_shop_promoted AS "综合费比(店铺被投)",
    t.total_expense_rate_net_refund_shop_bound AS "综合费比(剔除退款、店铺绑定)",
    t.total_expense_rate_net_refund_shop_promoted AS "综合费比(剔除退款、店铺被投)",
    t.batch_id AS "导入批次ID",
    t.source_sheet_name AS "源工作表名称",
    t.source_row_number AS "源文件行号",
    t.imported_at AS "写入时间"
FROM core.douyin_carrier_daily t
JOIN meta.shop s ON t.shop_id = s.shop_id;

DROP VIEW IF EXISTS "中文数据"."抖音账号日报";
CREATE VIEW "中文数据"."抖音账号日报" AS
SELECT
    t.row_id AS "数据行ID",
    s.shop_name AS "店铺名称",
    t.biz_date AS "日期",
    t.account_name AS "账号名称",
    t.account_type AS "账号类型",
    t.sale_scope AS "自营/合作",
    t.douyin_account_id AS "抖音号",
    t.transaction_amount AS "成交金额",
    t.user_pay_amount AS "用户支付金额",
    t.settlement_amount AS "结算金额",
    t.transaction_refund_amount_pay_time AS "成交退款金额(支付时间)",
    t.refund_amount_pay_time AS "退款金额(支付时间)",
    t.refund_rate_pay_time AS "退款率(支付时间)",
    t.ad_attributed_transaction_amount AS "投放贡献成交金额",
    t.ad_attributed_transaction_share AS "投放贡献成交占比",
    t.ad_spend_shop_promoted AS "投放消耗(店铺被投)",
    t.ad_spend_rate_net_refund_shop_promoted AS "投放费比(剔除退款、店铺被投)",
    t.exposure_to_click_rate_users AS "商品曝光-点击转化率(人数)",
    t.click_to_transaction_rate_users AS "商品点击-成交转化率(人数)",
    t.smart_coupon_amount AS "智能优惠券金额",
    t.platform_subsidy_amount AS "平台补贴金额",
    t.creator_subsidy_amount AS "达人补贴金额",
    t.presale_deposit_amount AS "预售定金",
    t.transaction_order_count AS "成交订单数",
    t.transaction_item_count AS "成交件数",
    t.avg_item_amount AS "件单价",
    t.transaction_buyer_count AS "成交人数",
    t.avg_customer_amount AS "客单价",
    t.net_transaction_amount AS "净成交金额",
    t.net_transaction_order_count AS "净成交订单量",
    t.settlement_amount_7d AS "7日结算金额",
    t.settlement_amount_14d AS "14日结算金额",
    t.settlement_amount_refund_time AS "结算金额(退款时间)",
    t.ad_attributed_settlement_amount AS "投放贡献结算金额",
    t.net_user_pay_amount_pay_time AS "退款后用户支付金额(支付时间)",
    t.net_smart_coupon_amount_pay_time AS "退款后智能优惠券金额(支付时间)",
    t.net_platform_subsidy_amount_pay_time AS "退款后平台补贴金额(支付时间)",
    t.net_creator_subsidy_amount_pay_time AS "退款后达人补贴金额(支付时间)",
    t.refund_order_count_pay_time AS "退款订单数(支付时间)",
    t.transaction_refund_amount_refund_time AS "成交退款金额(退款时间)",
    t.refund_amount_refund_time AS "退款金额(退款时间)",
    t.refund_order_count_refund_time AS "退款订单数(退款时间)",
    t.one_hour_transaction_refund_amount_pay_time AS "1小时成交退款金额(支付时间)",
    t.one_hour_refund_order_count_pay_time AS "1小时退款订单数(支付时间)",
    t.one_hour_refund_rate_pay_time AS "1小时退款率(支付时间)",
    t.ad_attributed_transaction_refund_amount_pay_time AS "投放贡献成交退款金额(支付时间)",
    t.ad_attributed_refund_rate_pay_time AS "投放部分退款率(支付时间)",
    t.product_exposure_count AS "商品曝光次数",
    t.product_click_count AS "商品点击次数",
    t.exposure_to_click_rate_events AS "商品曝光-点击转化率(次数)",
    t.click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    t.exposure_to_transaction_rate_events AS "商品曝光-成交转化率(次数)",
    t.product_exposure_user_count AS "商品曝光人数",
    t.product_click_user_count AS "商品点击人数",
    t.exposure_to_transaction_rate_users AS "商品曝光-成交转化率(人数)",
    t.user_pay_amount_per_1000_exposures AS "千次曝光用户支付金额",
    t.ad_spend_shop_bound AS "投放消耗(店铺绑定)",
    t.platform_commission_settlement AS "平台佣金(结算口径)",
    t.creator_commission_settlement AS "达人佣金(结算口径)",
    t.ad_spend_rate_shop_bound AS "投放费比(店铺绑定)",
    t.ad_spend_rate_shop_promoted AS "投放费比(店铺被投)",
    t.ad_spend_rate_net_refund_shop_bound AS "投放费比(剔除退款、店铺绑定)",
    t.total_expense_rate_shop_bound AS "综合费比(店铺绑定)",
    t.total_expense_rate_shop_promoted AS "综合费比(店铺被投)",
    t.total_expense_rate_net_refund_shop_bound AS "综合费比(剔除退款、店铺绑定)",
    t.total_expense_rate_net_refund_shop_promoted AS "综合费比(剔除退款、店铺被投)",
    t.batch_id AS "导入批次ID",
    t.source_sheet_name AS "源工作表名称",
    t.source_row_number AS "源文件行号",
    t.imported_at AS "写入时间"
FROM core.douyin_account_daily t
JOIN meta.shop s ON t.shop_id = s.shop_id;

DROP VIEW IF EXISTS "中文数据"."抖音内容日报";
CREATE VIEW "中文数据"."抖音内容日报" AS
SELECT
    t.row_id AS "数据行ID",
    s.shop_name AS "店铺名称",
    t.biz_date AS "日期",
    t.selling_type AS "售卖类型",
    t.carrier_type AS "载体类型",
    t.content_id AS "ID",
    t.content_title AS "标题/名称",
    t.transaction_amount AS "成交金额",
    t.user_pay_amount AS "用户支付金额",
    t.settlement_amount AS "结算金额",
    t.transaction_refund_amount_pay_time AS "成交退款金额(支付时间)",
    t.refund_amount_pay_time AS "退款金额(支付时间)",
    t.refund_rate_pay_time AS "退款率(支付时间)",
    t.ad_attributed_transaction_amount AS "投放贡献成交金额",
    t.ad_attributed_transaction_share AS "投放贡献成交占比",
    t.ad_spend_shop_promoted AS "投放消耗(店铺被投)",
    t.ad_spend_rate_net_refund_shop_promoted AS "投放费比(剔除退款、店铺被投)",
    t.exposure_to_click_rate_users AS "商品曝光-点击转化率(人数)",
    t.click_to_transaction_rate_users AS "商品点击-成交转化率(人数)",
    t.smart_coupon_amount AS "智能优惠券金额",
    t.platform_subsidy_amount AS "平台补贴金额",
    t.creator_subsidy_amount AS "达人补贴金额",
    t.presale_deposit_amount AS "预售定金",
    t.transaction_order_count AS "成交订单数",
    t.transaction_item_count AS "成交件数",
    t.avg_item_amount AS "件单价",
    t.transaction_buyer_count AS "成交人数",
    t.avg_customer_amount AS "客单价",
    t.net_transaction_amount AS "净成交金额",
    t.net_transaction_order_count AS "净成交订单量",
    t.settlement_amount_7d AS "7日结算金额",
    t.settlement_amount_14d AS "14日结算金额",
    t.settlement_amount_refund_time AS "结算金额(退款时间)",
    t.ad_attributed_settlement_amount AS "投放贡献结算金额",
    t.net_user_pay_amount_pay_time AS "退款后用户支付金额(支付时间)",
    t.net_smart_coupon_amount_pay_time AS "退款后智能优惠券金额(支付时间)",
    t.net_platform_subsidy_amount_pay_time AS "退款后平台补贴金额(支付时间)",
    t.net_creator_subsidy_amount_pay_time AS "退款后达人补贴金额(支付时间)",
    t.refund_order_count_pay_time AS "退款订单数(支付时间)",
    t.transaction_refund_amount_refund_time AS "成交退款金额(退款时间)",
    t.refund_amount_refund_time AS "退款金额(退款时间)",
    t.refund_order_count_refund_time AS "退款订单数(退款时间)",
    t.one_hour_transaction_refund_amount_pay_time AS "1小时成交退款金额(支付时间)",
    t.one_hour_refund_order_count_pay_time AS "1小时退款订单数(支付时间)",
    t.one_hour_refund_rate_pay_time AS "1小时退款率(支付时间)",
    t.ad_attributed_transaction_refund_amount_pay_time AS "投放贡献成交退款金额(支付时间)",
    t.ad_attributed_refund_rate_pay_time AS "投放部分退款率(支付时间)",
    t.product_exposure_count AS "商品曝光次数",
    t.product_click_count AS "商品点击次数",
    t.exposure_to_click_rate_events AS "商品曝光-点击转化率(次数)",
    t.click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    t.exposure_to_transaction_rate_events AS "商品曝光-成交转化率(次数)",
    t.product_exposure_user_count AS "商品曝光人数",
    t.product_click_user_count AS "商品点击人数",
    t.exposure_to_transaction_rate_users AS "商品曝光-成交转化率(人数)",
    t.user_pay_amount_per_1000_exposures AS "千次曝光用户支付金额",
    t.ad_spend_shop_bound AS "投放消耗(店铺绑定)",
    t.platform_commission_settlement AS "平台佣金(结算口径)",
    t.creator_commission_settlement AS "达人佣金(结算口径)",
    t.ad_spend_rate_shop_bound AS "投放费比(店铺绑定)",
    t.ad_spend_rate_shop_promoted AS "投放费比(店铺被投)",
    t.ad_spend_rate_net_refund_shop_bound AS "投放费比(剔除退款、店铺绑定)",
    t.total_expense_rate_shop_bound AS "综合费比(店铺绑定)",
    t.total_expense_rate_shop_promoted AS "综合费比(店铺被投)",
    t.total_expense_rate_net_refund_shop_bound AS "综合费比(剔除退款、店铺绑定)",
    t.total_expense_rate_net_refund_shop_promoted AS "综合费比(剔除退款、店铺被投)",
    t.batch_id AS "导入批次ID",
    t.source_sheet_name AS "源工作表名称",
    t.source_row_number AS "源文件行号",
    t.imported_at AS "写入时间"
FROM core.douyin_content_daily t
JOIN meta.shop s ON t.shop_id = s.shop_id;

DROP VIEW IF EXISTS "中文数据"."抖音终端日报";
CREATE VIEW "中文数据"."抖音终端日报" AS
SELECT
    t.row_id AS "数据行ID",
    s.shop_name AS "店铺名称",
    t.biz_date AS "日期",
    t.terminal_type AS "终端类型",
    t.selling_type AS "售卖类型",
    t.transaction_amount AS "成交金额",
    t.user_pay_amount AS "用户支付金额",
    t.settlement_amount AS "结算金额",
    t.transaction_order_count AS "成交订单数",
    t.transaction_refund_amount_pay_time AS "成交退款金额(支付时间)",
    t.refund_rate_pay_time AS "退款率(支付时间)",
    t.product_exposure_count AS "商品曝光次数",
    t.product_click_count AS "商品点击次数",
    t.exposure_to_click_rate_events AS "商品曝光-点击转化率(次数)",
    t.click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    t.smart_coupon_amount AS "智能优惠券金额",
    t.platform_subsidy_amount AS "平台补贴金额",
    t.creator_subsidy_amount AS "达人补贴金额",
    t.presale_deposit_amount AS "预售定金",
    t.transaction_item_count AS "成交件数",
    t.avg_item_amount AS "件单价",
    t.settlement_amount_7d AS "7日结算金额",
    t.settlement_amount_14d AS "14日结算金额",
    t.settlement_amount_refund_time AS "结算金额(退款时间)",
    t.ad_attributed_settlement_amount AS "投放贡献结算金额",
    t.net_user_pay_amount_pay_time AS "退款后用户支付金额(支付时间)",
    t.net_smart_coupon_amount_pay_time AS "退款后智能优惠券金额(支付时间)",
    t.net_platform_subsidy_amount_pay_time AS "退款后平台补贴金额(支付时间)",
    t.net_creator_subsidy_amount_pay_time AS "退款后达人补贴金额(支付时间)",
    t.refund_amount_pay_time AS "退款金额(支付时间)",
    t.refund_order_count_pay_time AS "退款订单数(支付时间)",
    t.transaction_refund_amount_refund_time AS "成交退款金额(退款时间)",
    t.refund_amount_refund_time AS "退款金额(退款时间)",
    t.refund_order_count_refund_time AS "退款订单数(退款时间)",
    t.one_hour_transaction_refund_amount_pay_time AS "1小时成交退款金额(支付时间)",
    t.one_hour_refund_order_count_pay_time AS "1小时退款订单数(支付时间)",
    t.one_hour_refund_rate_pay_time AS "1小时退款率(支付时间)",
    t.exposure_to_transaction_rate_events AS "商品曝光-成交转化率(次数)",
    t.user_pay_amount_per_1000_exposures AS "千次曝光用户支付金额",
    t.batch_id AS "导入批次ID",
    t.source_sheet_name AS "源工作表名称",
    t.source_row_number AS "源文件行号",
    t.imported_at AS "写入时间"
FROM core.douyin_terminal_daily t
JOIN meta.shop s ON t.shop_id = s.shop_id;

DROP VIEW IF EXISTS "中文数据"."抖音类目日报";
CREATE VIEW "中文数据"."抖音类目日报" AS
SELECT
    t.row_id AS "数据行ID",
    s.shop_name AS "店铺名称",
    t.biz_date AS "日期",
    t.category_level_1 AS "一级类目",
    t.category_level_2 AS "二级类目",
    t.category_level_3 AS "三级类目",
    t.category_level_4 AS "四级类目",
    t.user_pay_amount AS "用户支付金额",
    t.avg_transaction_order_amount AS "成交笔单价",
    t.click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    t.refund_amount_pay_time AS "退款金额(支付时间)",
    t.refund_rate_pay_time AS "退款率(支付时间)",
    t.batch_id AS "导入批次ID",
    t.source_sheet_name AS "源工作表名称",
    t.source_row_number AS "源文件行号",
    t.imported_at AS "写入时间"
FROM core.douyin_category_daily t
JOIN meta.shop s ON t.shop_id = s.shop_id;

DROP VIEW IF EXISTS "中文数据"."抖音商品日报";
CREATE VIEW "中文数据"."抖音商品日报" AS
SELECT
    t.row_id AS "数据行ID",
    s.shop_name AS "店铺名称",
    t.biz_date AS "日期",
    t.product_name AS "商品名称",
    t.product_id AS "商品编号",
    t.carrier_type AS "载体类型",
    t.user_pay_amount AS "用户支付金额",
    t.avg_transaction_order_amount AS "成交笔单价",
    t.click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    t.refund_amount_pay_time AS "退款金额(支付时间)",
    t.refund_rate_pay_time AS "退款率(支付时间)",
    t.smart_coupon_amount AS "智能优惠券金额",
    t.platform_subsidy_amount AS "电商平台补贴金额",
    t.net_smart_coupon_amount_pay_time AS "退款后智能优惠券金额(支付时间)",
    t.net_platform_subsidy_amount_pay_time AS "退款后电商平台补贴金额(支付时间)",
    t.batch_id AS "导入批次ID",
    t.source_sheet_name AS "源工作表名称",
    t.source_row_number AS "源文件行号",
    t.imported_at AS "写入时间"
FROM core.douyin_product_daily t
JOIN meta.shop s ON t.shop_id = s.shop_id;

DROP VIEW IF EXISTS "中文数据"."抖音价格带日报";
CREATE VIEW "中文数据"."抖音价格带日报" AS
SELECT
    t.row_id AS "数据行ID",
    s.shop_name AS "店铺名称",
    t.biz_date AS "日期",
    t.price_band AS "价格带",
    t.user_pay_amount AS "用户支付金额",
    t.avg_transaction_order_amount AS "成交笔单价",
    t.click_to_transaction_rate_events AS "商品点击-成交转化率(次数)",
    t.batch_id AS "导入批次ID",
    t.source_sheet_name AS "源工作表名称",
    t.source_row_number AS "源文件行号",
    t.imported_at AS "写入时间"
FROM core.douyin_price_band_daily t
JOIN meta.shop s ON t.shop_id = s.shop_id;

DROP VIEW IF EXISTS "中文数据"."抖音人群日报";
CREATE VIEW "中文数据"."抖音人群日报" AS
SELECT
    t.row_id AS "数据行ID",
    s.shop_name AS "店铺名称",
    t.biz_date AS "日期",
    t.audience_type AS "人群类型",
    t.carrier_type AS "载体类型",
    t.user_pay_amount AS "用户支付金额",
    t.transaction_buyer_count AS "成交人数",
    t.avg_customer_amount AS "客单价",
    t.transaction_order_count AS "成交订单数",
    t.repeat_user_repeat_rate AS "复购用户复购率",
    t.batch_id AS "导入批次ID",
    t.source_sheet_name AS "源工作表名称",
    t.source_row_number AS "源文件行号",
    t.imported_at AS "写入时间"
FROM core.douyin_audience_daily t
JOIN meta.shop s ON t.shop_id = s.shop_id;

COMMIT;